# Generated by Django 5.2.17 on 2026-09-27 17:03

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='обозначение')),
                ('note', models.CharField(blank=True, max_length=64, verbose_name='категория')),
            ],
            options={
                'verbose_name': 'единица измерения',
                'verbose_name_plural': 'единицы измерения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменён')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='analyses.unit', verbose_name='единица измерения')),
            ],
            options={
                'verbose_name': 'анализ',
                'verbose_name_plural': 'анализы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64, verbose_name='значение')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата и время сдачи')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='внесено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='analyses.analysis', verbose_name='анализ')),
            ],
            options={
                'verbose_name': 'значение анализа',
                'verbose_name_plural': 'значения анализов',
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['analysis', '-measured_at'], name='idx_value_analysis_measured')],
            },
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['user', 'name'], name='idx_analysis_user_name'),
        ),
        migrations.AddConstraint(
            model_name='analysis',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='uq_analysis_user_name_ci'),
        ),
    ]
